In [1]:
# Array creation
# 1.	Create a numpy array of size 10, filled with zeros
import numpy as np
array_z=np.zeros(10)
array_z


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# 2.	Create a numpy array with values ranging from 10 to 49 and set its datatype to float

#(Hint: Remember that you can set a specific dtype while defining an array for e.g. 
#Arr1 =np.array([1,2,3,4,5]) #defines an int array by default
#Arr2 =np.array([1,2,3,4,5], dtype = float) #specifying the dtype as an argument will create a float array). 
array_f = np.arange(10, 50, dtype=float)
array_f


array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

In [10]:
#3.	Create a numpy matrix of 2*2 integers, filled with ones.
ones_matrix = np.ones((2, 2), dtype=int)
ones_matrix

array([[1, 1],
       [1, 1]])

In [11]:
#4.	Create a numpy matrix of 3*2 float numbers, filled with ones.
ones_matrix= np.ones ((3,2),dtype=float)
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# 5.	Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones. (#hint: search the function np.ones_like( ) )
X = np.array([[7,8,9], [10,11,12]])
new_array_ones= np.ones_like(X)
new_array_ones


array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
# 6.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros. (hint: similar function as above exists for zeros as well)
new_array_z= np.zeros_like(X)
new_array_z

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
#7.	Create a numpy matrix of 4*4 integers, filled with fives.
fives_matrix= np.full((4,4),5,dtype=int)
fives_matrix

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [17]:
#8.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
seven_matrix= np.full_like(X,7)
seven_matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [18]:
# 9.	Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
matrix_identity= np.eye(3)
matrix_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#10.	Create a numpy array, filled with 3 random integer values between 1 and 10.
random_array=np.random.randint(1,11,3)
random_array


array([6, 4, 9])

In [21]:
# 11.	Create a 3*3*3 numpy matrix, filled with random float values.
float_random_matrix= np.random.rand(3,3,3)
float_random_matrix

array([[[0.55373224, 0.02279883, 0.81196782],
        [0.50041272, 0.76339624, 0.11692712],
        [0.71114231, 0.43916495, 0.96138031]],

       [[0.99755293, 0.02705985, 0.96746185],
        [0.21632496, 0.20599733, 0.47529544],
        [0.3035737 , 0.41016644, 0.81287617]],

       [[0.01988808, 0.86182795, 0.97982639],
        [0.0795259 , 0.50912494, 0.27257584],
        [0.01148741, 0.61917892, 0.25841471]]])

In [22]:
# 12.	Create a numpy array with numbers from 1 to 10
numpy_array= np.arange(1,11)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
#13.	Create a numpy array with the odd numbers between 1 to 10.
array_odd=np.arange(1,11,2)
array_odd

array([1, 3, 5, 7, 9])

In [28]:
# 14.	Create a numpy array with numbers from 1 to 10, in descending order.
array_desc=np.arange(10,0,-1)
array_desc

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [30]:
# 15.	Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
ranging_matrix= np.arange(9).reshape(3,3)
ranging_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
#Array indexing:
# 1.	Given the X numpy array, show its first element

#X = np.array(['A','B','C','D','E'])

X=np.array(['A','B','C','D','E'])
first_element = X[0]
first_element


'A'

In [36]:
# 2.	Given the X numpy array, show its last element

#X = np.array(['A','B','C','D','E'])
last_element=X[4]
last_element




'E'

In [39]:
# 3.	Given the X numpy array, show its first three elements

#X = np.array(['A','B','C','D','E'])
first_three_element= X[:3]
first_three_element

array(['A', 'B', 'C'], dtype='<U1')

In [40]:
# 4.	Given the X numpy array, show all middle elements

#X = np.array(['A','B','C','D','E'])
middle_element=X[1:-1]
middle_element


array(['B', 'C', 'D'], dtype='<U1')

In [41]:
# 5.	Given the X numpy array, show the elements in reverse position.

#X = np.array(['A','B','C','D','E'])
reverse_array=X[::-1]
reverse_array



array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [45]:
#6.	Given the X numpy array, show the elements in an odd position.

#X = np.array(['A','B','C','D','E'])

odd_array= X[::2]
odd_array


array(['A', 'C', 'E'], dtype='<U1')

In [7]:
#7.	Given the X numpy matrix, show the first row’s elements.

#X = np.array([
   # [1,   2,  3,  4],
   # [5,   6,  7,  8],
   # [9,  10, 11, 12],
   # [13, 14, 15, 16]
#])



X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

first_row_elements = X[0]
first_row_elements




array([1, 2, 3, 4])

In [8]:
#8.	Given the X numpy matrix, show the last row elements.

#X = np.array([
    #[1,   2,  3,  4],
    #[5,   6,  7,  8],
    #[9,  10, 11, 12],
    #[13, 14, 15, 16]
#])

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

last_row_element= X[3]
last_row_element



array([13, 14, 15, 16])

In [9]:
#9.	Given the X numpy matrix, show the first element on first row

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
first_element_first_row= X[0,1]
first_element_first_row


2

In [6]:
#10.	Given the X numpy matrix, show the last element on last row.


X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])


last_element_last_row = X[3,3]
last_element_last_row



16

In [7]:
#11.	Given the X numpy matrix, show the first two elements on the first two rows.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
first_two_first_two_rows= X[:2,:2]
first_two_first_two_rows
    


array([[1, 2],
       [5, 6]])

In [9]:
# 12.	Given the X numpy matrix, show the last two elements on the last two rows

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
last_two_last_two_rows= X[2:,2:]
last_two_last_two_rows
    


array([[11, 12],
       [15, 16]])

In [11]:
# Array manipulation
#1.	Convert the given integer numpy array to float (you need to google the function that will help you do this)

X = np.array([-5, -3, 0, 10, 40])
X_float = X.astype(float)
X_float


array([-5., -3.,  0., 10., 40.])

In [16]:
# 2.	Reverse the given numpy array (first element becomes last) through indexing

X = [-5, -3, 0, 10, 40]
reverse_array= X[::-1]
reverse_array


[40, 10, 0, -3, -5]

In [17]:
#3.	Given the X numpy array, set the fifth element equal to 1

X = np.zeros(10)
X[4]=1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#4.	Given the X numpy matrix, change the last row with all 1

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[3]=1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [19]:
#5.	Given the X numpy matrix, add 5 to every element

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X+=5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])